### ISSUE TITLE
Coding scheme load failure

### ISSUE THREAD

**Issue by lukechurch** [lukechurch/coda#103]
When importing a coding scheme, it loads two columns of the same scheme. When deleting one column both disappear. 

When trying to load a coding scheme again after this, we can select the coding scheme from the open file popup, click open, the popup disappears but the coding scheme doesn't load.

**Comment by as2388** [comment]
There are two parts to solving this:
- [ ] Fix displaying two columns with the same name, and deleting both
- [ ] Fix unable to upload a scheme after deleting one.

**Comment by as2388** [comment]
The unable to load a scheme after deleting bug is only occurring for me if I try to add the scheme which was just deleted.
